<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Finder extends Model
{
    use HasFactory;

    protected $table = 'finder';  // your table name

    protected $fillable = [
        'lot',
        'date',
        'time',
        'platform',
        'center',
        'auction_name',
        'auction_type',
        'auction_id',
        'title',
        'images',
        'vehicle_type',
        'make',
        'model',
        'variant',
        'body_type',
        'year',
        'doors',
        'seats',
        'fuel_type',
        'transmission',
        'cc',
        'drivetrain',
        'euro_status',
        'dor',
        'reg',
        'former_keepers',
        'mileage',
        'mileage_warranted',
        'mot_expiry_date',
        'mot_due',
        'v5',
        'v5_location',
        'keyss',
        'vat_status',
        'colour',
        'service_history',
        'number_of_services',
        'number_of_services_details',
        'last_service',
        'last_service_mileage',
        'number_of_stamps',
        'service_indicator_light_illuminated',
        'dvsa_mileage',
        'service_notes',
        'tyres_condition',
        'grade',
        'exterior_grade',
        'interior_grade',
        'condition_report_text',
        'inspection_report',
        'other_report_name',
        'other_report_details',
        'other_report',
        'inspection_date',
        'bidding_history',
        'last_bid',
        'bidding_status',
        'estimated_price',
        'cap_new',
        'cap_retail',
        'cap_clean',
        'cap_average',
        'cap_below',
        'glass_new',
        'glass_retail',
        'glass_trade',
        'autotrader_retail',
        'additional_information',
        'chassis_no',
        'base_colour',
        'colour_type',
        'interior_colour',
        'colour_trim',
        'trim_type',
        't_loss',
        'imported',
        'nox_emissions',
        'co2_emissions',
        'declarations',
        'equipment',
        'powered_by'
    ];
}
